name: End-to-end tests
on:
  push:
    branches: [ dev ]

  pull_request:
    branches: [ main ]
    
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      # Install dependencies with caching
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7