pipeline {
    agent {
        docker {
            image 'cypress/browsers:latest'
            args '-u root:root'
        }
    }

    triggers {
        cron('H/30 * * * *')
    }

    stages {
        stage('Install Dependencies') {
            steps {
                dir('projetos/SwagLabs') {
                    sh 'npm ci'
                }
            }
        }

        stage('Cypress Run - Smoke') {
            steps {
                dir('projetos/SwagLabs') {
                    sh 'npx cypress run --spec "cypress/e2e/smoke/*.cy.js" --reporter mochawesome'
                }
            }
        }
    }

    post {
        always {
            sh 'chown -R 1000:1000 .'
            dir('projetos/SwagLabs') {
                junit allowEmptyResults: true, testResults: 'cypress/reports/*.xml'
                archiveArtifacts artifacts: 'cypress/reports/**', allowEmptyArchive: true
                archiveArtifacts artifacts: 'cypress/screenshots/**', allowEmptyArchive: true
                archiveArtifacts artifacts: 'cypress/videos/**', allowEmptyArchive: true
            }
        }
    }
}