name: Smoke Tests - ServeRest API
on:
  push:
    branches: "**"
    
jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        
      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Newman run
        working-directory: Projetos/ServeRestAPI
        run: npm ci

      - name: Execute API tests
        working-directory: Projetos/ServeRestAPI
        run: |
          npx newman run postman/ServeRestAPI-Smoke.postman_collection.json \
          -e postman/ServeRest.postman_environment.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export newman-report.html    

      - name: Upload newman report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: Projetos/ServeRestAPI/newman-report.html
          if-no-files-found: ignore   